name: cky
channels:
- anaconda/cloud/conda-forge
- anaconda/cloud/intel
- anaconda/pkgs/main
- conda-forge
- intel
- nvidia
- pytorch
dependencies:
- abseil-cpp
- absl-py
- accimage
- aiohttp
- alabaster
- alsa-lib
- antlr-python-runtime
- aom
- archspec
- astropy
- async-timeout
- attr
- attrs
- backports.cached-property
- boltons
- brotlipy
- cachecontrol
- cachecontrol-with-filecache
- cfitsio
- cleo
- crashtest
- cudatoolkit
- cudnn=8.9.2.26
- cupti
- dulwich
- easydict
- ffmpeg=4.4.2
- fftw
- fmt
- freeglut
- graphite2=1.3.14
- grpc-cpp
- grpcio
- gstreamer-orc
- gtest
- harfbuzz=4.4.1
- hdf5
- html5lib
- imagecodecs
- importlib_metadata
- iniconfig
- intel-openmp
- ipp
- ipp-devel
- ipykernel
- jack
- jasper
- jpeg
- jsonpatch
- jsonpointer
- jsonschema
- keyring
- lcms2=2.14
- libarchive=3.6.2
- libass
- libedit=3.1.20230828
- libhwloc
- libmagma
- libmagma_sparse
- libogg=1.3.5
- libopenblas
- libopencv
- libsolv
- libtool
- libudev1
- lockfile
- magma
- matplotlib
- mpld3
- ninja
- omegaconf=2.3
- openblas
- pandas
- pexpect=4.8
- pillow=10.0.1
- pluggy
- pooch
- poppy
- pulseaudio
- pybind11-abi
- pycosat
- pyrsistent
- python=3.11
- python-tzdata
- pytorch
- pytorch-cuda=12.4
- qt
- qt-main
- qt-webengine
- reproc
- reproc-cpp
- requests-toolbelt
- ruamel.yaml
- safetensors=0.4
- scikit-image
- scikit-learn
- screeninfo
- setuptools
- shellingham
- sphinx
- tabulate
- tbb
- tensorboard
- tensorboardx
- tifffile=2022
- timm
- tomlkit
- toolz
- torchaudio
- torchvision
- transformers
- trove-classifiers
- truststore
- typing
- virtualenv
- webencodings
- yaml-cpp
- zstandard

